HED-schema.mediawiki

remove white space for root level tags syntax

---

HED-schema.mediawiki
hedxml-unitdev/HEDv1.0.0-unitdev.xml

Added ^ to designate exponent in units.

Hed unitdev use ^ as exponent

---

HED-schema.mediawiki
hedxml-devunit/HEDv1.0.0-devunit.xml
hedxml-devunit/HEDv1.2.0-devunit.xml

Added multiples and submultiples to the unit specifications

Hed devunit

---

HED-schema-reduced.mediawiki

I make all of the changes that we discussed. There are still some items that need to be discussed.

Updates to Action and Participant categories

---

HED-schema-reduced.mediawiki

The Item modifications are not done in this.

Updating Item, Action and Participant sections

---

HED-schema.mediawiki

Added unit modifiers to the master branch.

Added unit modifiers to master version

---

HED-schema.mediawiki

Fixed more extraneous quotes

---

HED-schema-reduced.mediawiki
HED-schema.mediawiki

Fixed unwanted quotes in the wikimedia file

---

hedxml-restruct/HEDv1.6.1-restruct.xml

Added new version of HED restructured to include clockTime units

Added HEDv1.6.1-restruct.xml to repository to include clockTime units

---

hedxml/HED7.1.1.xml

Added new version of HED restructured to include clockTime units

Added the HED7.1.1.xml to the HED-restructure branch

---

HED-schema-reduced.mediawiki

Added Definition tag and updated scope description

---

HED-schema-reduced.mediawiki
hedxml/HED7.1.1.xml

This is a first pass at restructuring with naming that has no conflicts. It will form a basis for development. Still many sections need work.

Restructured reduced schema with meaningful nodes

---

HED-schema-reduced.mediawiki

Reorganized Action and corrected Sensory/Visual

---

HED-schema.mediawiki
hedxml/HED7.1.1.xml
hedxml/HEDLatest.xml

Also cleaned up the clockTime unit class and added the dateTime unit class.

Fixed some missing extensionAllowed attributes

---

HED-schema-reduced.mediawiki
hedxml-reduced/HEDReduced080620.xml

Revised so that we can discuss

Did more work for discussion

---

HED-schema-reduced.mediawiki
hedxml-reduced/HEDLatest-reduced.xml

Changes temporarily in for the viewer.

With todays changes

---

HED-schema-reduced.mediawiki

Another merge of an intermediate version

---

HED-schema-reduced.mediawiki
hedxml-reduced/HEDLatest-reduced.xml

Another pull request since Categorical does not show up

---

HED-schema-reduced.mediawiki
hedxml-reduced/HEDLatest-reduced.xml

Additional reorganization

---

HED-generation3-schema.mediawiki
hedxml/HED8.0.0-alpha.1.xml

Moved Organizational back to Attribute also

Updated Organizational-property back to Organizational

---

HED-generation3-schema-V8.0.0-alpha.1.mediawiki
hedxml/HED8.0.0-alpha.1.xml

Had to back this out of version 1 so the online HEDtools will run.

Temporarily removed posixPath unitClass

---

HED-generation3-schema-V8.0.0-alpha.2.mediawiki

This addition is to the mediawiki version 8.0.0-alpha.2 in order to help with XML conversion testing.

Added unitClassAttribute and unitModifierAttribute

---

HED-generation2-schema-7.3.0.mediawiki
HED-generation3-schema-8.0.0-alpha.1.mediawiki
HED-generation3-schema-8.0.0-alpha.2.mediawiki
README.md

Moving towards the new schema format.

Updated README and added unitClass as attribute in Schema attributes

---

hedxml-test/HED-generation3-schema-8.0.0-beta.3.mediawiki
hedxml-test/HED8.0.0-beta.3.xml

Minor typo corrections on mediawiki.

Corrected the dateTime value caps

---

hedxml-test/HED-generation3-schema-8.0.0-beta.5.mediawiki
hedxml-test/HED8.0.0-beta.5.xml

This is a work in progress and there will be several more modifications.

Separated properties from relationships

---

hedxml-test/HED-generation3-schema-8.0.0-beta.5.mediawiki

Also eliminated Thermal-relation

Moved Categorical to Property/Data-property/Data-type/Categorical-type

---

hedxml-test/HED8.0.0-beta.5.xml

Also eliminated Thermal-relation

Update the XML for the categorical change

---

hedxml-test/HED-generation3-schema-8.0.0-beta.5.mediawiki
hedxml-test/HED8.0.0-beta.5.xml

Also eliminated Thermal-relation

Updated Categorical-type indentation

---

hedxml-test/HED-generation3-schema-8.0.0-beta.5.mediawiki
hedxml-test/HED8.0.0-beta.5.xml

Updated the Sensory-properties to eliminate and extra level. 

---

hedxml-test/HED-generation3-schema-8.0.0-beta.5.mediawiki
hedxml-test/HED8.0.0-beta.5.xml

Corrected indentation of Organizational-property

---

README.md
hedxml-test/HED-generation3-schema-8.0.0-beta.5.mediawiki
hedxml-test/HED8.0.0-beta.5.xml

Provisional changes on Directional-relation

---

hedxml-test/HED-generation3-schema-8.0.0-beta.5.mediawiki
hedxml-test/HED8.0.0-beta.5.xml

Renamed Repetition-interval and Repetition-number

---

hedxml-test/HED-generation3-schema-8.0.0-beta.5.mediawiki
hedxml-test/HED8.0.0-beta.5.xml

Updated the Event-stream and Condition-variable to take labels

---

hedxml-test/HED-generation3-schema-8.0.0-beta.5.mediawiki
hedxml-test/HED8.0.0-beta.5.xml

Tagging of order in a sequence is to be done with Event-stream mechanism.

Eliminated Ordering-relation

---

hedspec/HEDspecification.md

Tables still need to be redone.

Finished rough pass through specification markdown 

---

PROPOSED.md

The purpose is to gather changes that need to be made to mediawiki before the next release. Also, items which have been raised but have not been resolved.

Added a PROPOSED.md

---

hedspec/css/watermark.css
hedspec/images/favicon.png
hedspec/images/logo.png
mkdocs.yml
readthedocs.yml
requirements.txt

Starting to work on the infrastructure for automatically building the specification docs.

Updated to have a yaml file for readthedocs

---

mkdocs.yml
themes/partials/footer.html

Corrected yml with missing themes directory

---

docs/01_Introduction.md
docs/02_Terminology.md
docs/03_Schema.md
docs/04_Basic_annotation.md
docs/05_Advanced_annotation.md
docs/06_Library_schema.md
docs/07_HED_with_BIDS.md
docs/08_Resources.md
docs/Appendix_A.md
docs/Appendix_B.md

Added admonition formatting boxes.

Continued reformatting of HED specification documentation

---

docs/01_Introduction.md
docs/03_Schema.md
docs/04_Basic_annotation.md

Added admonition formatting boxes.

Updated documentation layout and examples

---

docs/04_Basic_annotation.md

Added admonition formatting boxes.

Updated the format in the examples

---

docs/03_Schema.md
docs/04_Basic_annotation.md
docs/index.rst

Added admonition formatting boxes.

Trying different layouts and TOCs elements

---

PROPOSED.md
docs/07_Library_schema.md
prelease/HED8.0.1.mediawiki
prelease/HED8.0.1.xml

Started to correct patch-level omissions and corrections for release of 8.0.1.

Starting minor corrections for patch release

---

docs/requirements.txt
docs/source/Documentation.md
docs/source/conf.py
docs/source/index.rst

Sidebar still does not appear to be working on this repo.

Updated the documentation layout

---

docs/source/_template/layout.html
docs/source/index.rst

Still not able to get correct sidebar on readthedocs.

Minor changes to docs 

---

docs/source/03_HED_formats.md
docs/source/07_Library_schemas.md
docs/source/Appendix_B.md
docs/source/_static/data/error_tests/DEFINITION_INVALID.json

Incorporated suggestions from @happy5214 on Chapter 3 and errors.

Incorporated corrections on specification

---

docs/source/03_HED_formats.md
docs/source/05_Advanced_annotation.md
docs/source/07_Library_schemas.md
docs/source/Appendix_A.md
docs/source/Appendix_B.md
tests/json_tests/ONSET_OFFSET_INSET_ERROR.json

Also updated ONSET_OFFSET_INSET_ERROR description and tests.

Updated the partnered schema descriptions

---

.codespellrc
.github/workflows/codespell.yml
docs/source/03_HED_formats.md
docs/source/05_Advanced_annotation.md
docs/source/07_Library_schemas.md
docs/source/Appendix_B.md
hedwiki/HED7.2.0.mediawiki
hedwiki/HED7.3.0.mediawiki
hedwiki/HED8.0.0.mediawiki
hedwiki/HED8.1.0.mediawiki
hedwiki/HED8.2.0.mediawiki
hedxml/HED7.2.0.xml
hedxml/HED8.0.0.xml
hedxml/HED8.1.0.xml
hedxml/HED8.2.0.xml
hedxml/HEDLatest.xml

workflow would only detect when a new typo is introduced, it will not automagically inject its fix somehow.
more info on codespell: https://github.com/codespell-project/codespell
I have excluded `deprecated/`

add codespell: config, workflow and have typos fixed

---

tests/json_tests/TAG_GROUP_ERROR.json
tests/json_tests/TEMPORAL_TAG_ERROR_DELAY.json

Update one old test to new duration requirements

Add some tests for new Delay/duration rules.

---

.codespellrc
docs/source/Appendix_B.md
tests/all_tests.json
tests/json_tests/CHARACTER_INVALID.json
tests/json_tests/REQUIRED_TAG_MISSING.json
tests/json_tests/SIDECAR_INVALID.json
tests/json_tests/UNITS_MISSING.json
tests/nonschema_tests.json
tests/run_consolidate_tests.py
tests/test_summarize_testdata.py

Minor formatting updates in specification.

Updating the JSON tests to have all fields

---

tests/javascript_tests.json
tests/json_tests/DEFINITION_INVALID.json
tests/json_tests/TEMPORAL_TAG_ERROR_DELAY.json
tests/python_tests.json

Revised a few tests to better isolate the particular errors.

Corrected typos in the JSON spec-tests
